/**
 * This file was generated by the Jeddict
 */
package uk.me.mattgill.samples.jpa.sample.persistence.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@Entity
@NamedQueries({
    @NamedQuery(name = "item.getAll", query = "SELECT i FROM Item i"),
    @NamedQuery(name = "item.clearAll", query = "DELETE FROM Item")
})
public class Item implements Serializable {

    @Basic
    @Id
    private String name;

    @Basic
    private Integer count;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}